### ISSUE TITLE
Support of more than 4 dongles

### ISSUE THREAD

**Issue by iroks** [steve-m/librtlsdr#34]
it seems that the library supports only 4 parallel transmitting dongles at the moment.  If the fifth dongle is added and started to transfer data, e.g. rtl_test -d 4, the error message appears:
"Failed to submit transfer 3!"
"Library error -5, exiting..."

libusb is 1.0.21 (also tested with 1.0.19)

sdr_trunk is working fine on the same computer and supports at least 5 dongles.

**Comment by steve-m** [comment]
The issue is that the Kernel limits the maximum size of all buffers that libusb can allocate to 16MB by default. In order to disable the limit, you have to run the following command as root:

echo 0 > /sys/module/usbcore/parameters/usbfs_memory_mb

**Comment by iroks** [comment]
thanks, I did as described and  rtl_test is now working fine
