### ISSUE TITLE
Memory leak in rtlsdr_open() of librtlsdr.c

### ISSUE THREAD

**Issue by Perceval62** [steve-m/librtlsdr#49]
Calling rtlsdr_open() on an index that is already opened by another rtlsdr device causes a memory leak.

When 
~~~~
r = libusb_claim_interface(dev->devh, 0);
~~~~
fails @ line 1520 of librtlsdr.c, the memory space opened by libusb (@ line 1488)
~~~~
dev->devh 
~~~~
is never closed/freed by the code in the err tag.

This causes a memory leak when a second rtlsdr device is opened at the same index as another one that was succesfully opened.

Trying to call 
~~~~
"rtlsdr_close()"
~~~~
when rtlsdr_open() fails does not fix the problem because if this happens, the device handle given by rtlsdr_open() is invalid. Therefore, "rtlsdr_close()" has no way of freeing that memory space.

Proposed fix:
changing this at line 1520 of librtlsdr.c:
~~~~
r = libusb_claim_interface(dev->devh, 0);
if (r < 0) {
	fprintf(stderr, "usb_claim_interface error %d\n", r);
	goto err;
}
~~~~
for
~~~~
r = libusb_claim_interface(dev->devh, 0);
if (r < 0)
 {
	fprintf(stderr, "usb_claim_interface error %d\n", r);
	if (dev) 
	{
        	libusb_close(dev->devh);
	}
	goto err;
}
~~~~

Will ensure that the dev->devh that is dynamically allocated is freed if a claim error occurs.

Edit1: added a short paragraph at the top of the comment.

Edit2: created pull request #50 fixing the problem.

**Comment by Perceval62** [comment]
Forgot to say that the bug is reproducible by calling "rtlsdr_open()" twice (assuming the first time succeeds).

**Comment by steve-m** [comment]
Thanks, re-arranged your patch a bit and fixed the issue.

**Comment by Perceval62** [comment]
Thanks. 
This is an awesome project keep up the nice work !
