### ISSUE TITLE
Does not work on Kali 64 bit on raspberry pi

### ISSUE THREAD

**Issue by JasperGerth** [steve-m/librtlsdr#54]
I tried this on the raspberry pi 3b+ with Kali linux 64 bit.
rtl_test dit not work as the test stopped just after allocating the zero copy buffers

**Comment by vielmetti** [comment]
https://github.com/steve-m/librtlsdr/commit/81833a1cf6288fee93a9157c0f60cafb5ec340b9 has a patch which addresses this issue on arm64.
