### ISSUE TITLE
Problem building with cmake as sub project

### ISSUE THREAD

**Issue by leonsal** [steve-m/librtlsdr#59]

**Comment by leonsal** [comment]
When trying to build a simple project using librtlsdr as a subproject
using the following ```CMakeLists.txt``` and ```main.cpp```:

CMakeLists.txt:
```
make_minimum_required(VERSION 3.0 FATAL_ERROR)
project(rtl)
add_subdirectory(librtlsdr)
add_executable(rtl main.cpp)
target_link_libraries(rtl rtlsdr)
```
main.cpp:
```
#include <iostream>
#include "rtl-sdr.h"

int main() {

    auto ndevs = rtlsdr_get_device_count();
    std::cout << "device count:" << ndevs << "\n";
}
```
cmake generated errors like the following and others:
```
CMake Error at librtlsdr/CMakeLists.txt:44 (include):
  include could not find load file:
  Version
```
The problem seems to be that in the main librtlsdr/CMakeLists.txt file
the cmake module path is being set using CMAKE_SOURCE_DIR, which
in my case is the main project source directory.
Replacing the 3 occurances of  CMAKE_SOURCE_DIR by PROJECT_SOURCE_DIR 
in CMakeLists.txt seems to solve the problem.
If necessary I could make a PR.

Best regards.

**Comment by steve-m** [comment]
Hi,

thanks for reporting this. Can you open a pull request?

**Comment by leonsal** [comment]
OK. done.

**Comment by steve-m** [comment]
Thanks, merged.
